; PLANE_TILE.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 5
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", HOME

; Start of tile array.
PLANE_TILES::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $F8,$1F,$3C,$3C,$5E,$62,$5E,$62
DB $DF,$E3,$5E,$E3,$5E,$E3,$5E,$E3
DB $4E,$F3,$2C,$F7,$AD,$76,$EF,$F7
DB $2C,$34,$6E,$76,$8F,$F1,$FF,$FF
DB $03,$03,$1C,$1F,$60,$7F,$9E,$E1
DB $FF,$80,$7F,$40,$3F,$3F,$00,$00
DB $FC,$FC,$02,$FE,$7F,$81,$FF,$01
DB $FF,$01,$FE,$02,$FC,$FC,$00,$00
DB $1F,$F8,$3C,$3C,$5E,$62,$5E,$62
DB $DF,$E3,$5E,$E3,$5E,$E3,$5E,$E3
DB $00,$10,$00,$10,$10,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

; End of PLANE_TILE.Z80
